### ISSUE TITLE
[BUG] Text rendering is broken in Obsidian 1.0 outside of Reading mode

### ISSUE THREAD

**Issue by TheCourierNV** [MajorEnkidu/red-solitude-obsidian-theme#5]
**Describe the Bug**
I updated Obsidian to the new version and now every character will render on a separate line, like in the screenshot below.
It somehow fixes itself while in Reading mode

**Relevant Screenshots**
How it looks in every other mode:
![image](https://user-images.githubusercontent.com/58661940/195678901-35398337-385a-4a33-ad27-8fd66d03ed70.png)

How it looks like in Reading mode:
![image](https://user-images.githubusercontent.com/58661940/195681662-8870c0bf-f9fe-4523-8805-11bc73263f83.png)

**To Reproduce**
Open any obsidian vault after updating to Obsidian 1.0 and toggle off Reading mode

**In which mode does the bug occur?**
- [ ] Reading/Preview Mode
- [X] Source Mode
- [X] Live Preview

**Which editor are you using?**
- [ ] Legacy Editor
- [X] New Editor

**Which version of Obsidian are you using?**
- [X] Public Release (Desktop)
- [ ] Public Release (Mobile)
- [ ] Insider Release (Desktop)
- [ ] Insider Release (Mobile)

**Checklist**
- [X] I have updated to the latest version of the theme (`Obsidian Settings → Appearance → Themes - Manage → Update`).
- [X] I made sure that the issue is related to this theme, by checking that the issue does not occur with other themes or the default theme.

**Comment by MajorEnkidu** [comment]
Hi, thank you for posting this issue. I am currently working on a complete redesign of the theme.

**Comment by TheCourierNV** [comment]
This is fixed in the latest version, so I am going to close this.
Thank you for the speedy fix!
